shopware/recipes

shopware/core/6.4/manifest.json
.env often includes sensitive information like database credentials and API keys, it is a best practice to exclude this information from your repository
=> exclude sensitive information from your repository

shopware/platform/6.4/bin/watch-storefront.sh, shopware/storefront/6.4/bin/watch-storefront.sh
| Q             | A
| ------------- | ---
| License       | MIT
The hot reload proxy of `shopware/storefront` accepts a `PROXY_URL` environment variable which is currently not exported in the `watch-storefront.sh` script.
I'm using shopware in a DDEV setup with the hot proxy running on my host, so my proxy host and shopware host differ and the fallback to `APP_URL` no longer works.
But nevertheless, the hot proxy supports that variable so why not give it access to it ;) 
See: https://github.com/shopware/platform/blob/cfc39359c140edd71619b003779840b3499840fa/src/Storefront/Resources/app/storefront/build/start-hot-reload.js#L9
I'm not sure weather the "default" `watch-storefront.sh` script is affected by that.
I doesn't export `PROXY_URL`neither but I haven't tested it with a "default" …
=> Export PROXY_URL in watch-storefront.sh scripts

symfony/monolog-bundle/3.3/config/packages/dev/monolog.yaml, symfony/monolog-bundle/3.3/config/packages/prod/deprecations.yaml, symfony/monolog-bundle/3.3/config/packages/prod/monolog.yaml, symfony/monolog-bundle/3.3/config/packages/test/monolog.yaml, symfony/monolog-bundle/3.3/manifest.json
| Q             | A
| ------------- | ---
| License       | MIT
overrides monolog recipe to respect [shopware performance tweaks](https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks#logging) and sets the logging type to `rotating_file` like the shopware default (only in prod)
=> feat: add monolog override

shopware/core/6.4/manifest.json
According to symfony docs https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local the .gitignore should be adjusted
=> Change .gitignore for symfony recommended way

shopware/platform/6.4/bin/build-storefront.sh, shopware/storefront/6.4/bin/build-storefront.sh
**What was changed?**
I added the check for a new environment variable `SHOPWARE_SKIP_FEATURE_DUMP` so that the call of the `feature:dump` command in the script `bin/build-storefront.sh` can be skipped. All other console calls already had such an environment variable, only for the `feature:dump` it was missing.
**Why is this necessary?**
During a deployment the `feature:dump` command is not necessarily needed, because according to its own description it is meant for js testing and hot reloading. Thus, it should not be a problem to skip the command, if you don't need this things during deployment. Since it is the only PHP call that cannot be skipped, it is mandatory to have an environment where PHP is installed. If you can skip this command as well, you don't need to have PHP installed to …
=> Add environment variable to skip feature:dump when building the storefront

shopware/fastly-meta/6.4/config/fastly/recv.vcl
Disable stale_while_revalidate feature on Fastly SHIELD node to avoid caching issue when both soft-purges and shieding are used. Otherwise, it could happen that the SHIELD returns a stale object right after the purge request has been received, and the POP will cache this stale content if the Age<Max-Age.
=> Disable stale_while_revalidate on SHIELD node

shopware/administration/6.4/bin/build-administration.sh, shopware/administration/6.4/bin/watch-administration.sh, shopware/storefront/6.4/bin/build-storefront.sh, shopware/storefront/6.4/bin/watch-storefront.sh
Based on the [pull request](https://github.com/shopware/webpack-plugin-injector/pull/4) it would be nice if the dependency installation is also skipped if the matching environment variable isset.
=> Skip npm dependency installation if skipping env var isset

shopware/fastly-meta/6.4/bin/setup-fastly.sh
In case of errors in the VCL code, it can happens that the snippet exists in latest but not in active version.
=> Fix potential issue

frosh/devenv-meta/0.1/root/devenv.nix, frosh/devenv-meta/0.2/root/devenv.nix
As described here: https://developer.shopware.com/docs/guides/installation/devenv#faq
=> Devenv Environment variables: Use 127.0.0.1 instead of localhost

frosh/code-quality-meta/0.2/manifest.json, frosh/code-quality-meta/0.2/post-install.txt, frosh/code-quality-meta/0.2/root/ecs.php, frosh/code-quality-meta/0.2/root/phpstan.neon.dist, frosh/code-quality-meta/0.2/root/rector.php, frosh/code-quality-meta/0.2/vendor-bin/cs-fixer/composer.json, frosh/code-quality-meta/0.2/vendor-bin/phpstan/composer.json, frosh/code-quality-meta/0.2/vendor-bin/rector/composer.json
- I removed `SimplifyForeachToArrayFilterRector` from rector rules. See https://github.com/rectorphp/rector-src/commit/9df1445de8c8cb5eed5a85446628226f9b03ed76
- I changed the Namespace for SimpleFunctionAndFilterRector. See https://github.com/rectorphp/rector-symfony/commit/ed7129b58c0a2cef939ba2c4f858ef137da7edfa
- I increased rector to ^0.17.3
=> feat: update rector

shopware/paas-meta/6.4/.platform/applications.yaml, shopware/paas-meta/6.4/config/packages/paas.yaml
- Move JWT keys to variables instead of file system
- Disable web installer 
- Enable composer plugin loader by default
- Disable admin worker
- Remove Node dependency from deploy step
Updated documentation has been added in https://github.com/shopware/docs/pull/1090
=> BC-44 Improve PaaS Recipe & Docs

shopware/platform/6.4/bin/watch-storefront.sh, shopware/storefront/6.4/bin/watch-storefront.sh
Missing `export STOREFRONT_ASSETS_PORT` on `watch-storefront.sh`
It's used later on few places, like `Storefront/Resources/app/storefront/build/proxy-server-hot/index.js`, but because it was not exported, the value is `undefined`.
I also order the exports alphabetically.
Reference: https://github.com/shopware/platform/pull/3287
=> added missing "export STOREFRONT_ASSETS_PORT" on watch-storefront.sh

shopware/core/6.4/bin/ci
With https://github.com/shopware/recipes/commit/671f1a957ed89cf6d940792c4fb10eba469d1eb0 the constant was removed, but the use statement has been left there.
=> Remove unused use statement

shopware/administration/6.4/bin/build-administration.sh, shopware/administration/6.4/bin/watch-administration.sh, shopware/platform/6.4/bin/build-administration.sh, shopware/platform/6.4/bin/watch-administration.sh
Fix the Admin Build and Watch command
=> NEXT-30878 - fix admin build and watch

shopware/fastly-meta/6.4/config/fastly/recv/default.vcl
`client.ip` is always the immediate client of the current server. In Fastly terms, this means that in services that use shielding, the `client.ip` may be another Fastly server, not the 'actual' client. `Fastly-Client-IP` doesn't change when being forwarded from one Fastly server to another so will always represent the value of `client.ip` that was first seen by Fastly.
=> Use Fastly-Client-IP

shopware/core/6.6/bin/ci
https://github.com/shopware/shopware/pull/3472
=> fix(shopware6.6): Kernel logic in the ci command

shopware/administration/6.4/bin/build-administration.sh, shopware/administration/6.4/bin/watch-administration.sh, shopware/administration/6.6/bin/build-administration.sh, shopware/administration/6.6/bin/watch-administration.sh, shopware/platform/6.4/bin/build-administration.sh, shopware/platform/6.4/bin/build-storefront.sh, shopware/platform/6.4/bin/watch-administration.sh, shopware/platform/6.4/bin/watch-storefront.sh, shopware/platform/6.6/bin/build-administration.sh, shopware/platform/6.6/bin/build-storefront.sh, shopware/platform/6.6/bin/watch-administration.sh, shopware/platform/6.6/bin/watch-storefront.sh, shopware/storefront/6.4/bin/build-storefront.sh, shopware/storefront/6.4/bin/watch-storefront.sh, shopware/storefront/6.6/bin/build-storefront.sh, shopware/storefront/6.6/bin/watch-storefront.sh
I've fixed the typos in the bash scripts: without the change, the use of the placeholder variables is not working as intended.
See [shopware!3537](https://github.com/shopware/shopware/pull/3537) for more text.
=> fix typos in bash scripts

frosh/code-quality-meta/0.3/manifest.json, frosh/code-quality-meta/0.3/post-install.txt, frosh/code-quality-meta/0.3/root/ecs.php, frosh/code-quality-meta/0.3/root/phpstan.neon.dist, frosh/code-quality-meta/0.3/root/rector.php, frosh/code-quality-meta/0.3/vendor-bin/cs-fixer/composer.json, frosh/code-quality-meta/0.3/vendor-bin/phpstan/composer.json, frosh/code-quality-meta/0.3/vendor-bin/rector/composer.json
Use phpstan-bootstrap from Shopware core
Use latest frosh/shopware-rector version
=> fix: Add recipe for frosh/code-quality-meta:v0.3.0

shopware/core/6.4/bin/ci, shopware/core/6.4/bin/console, shopware/core/6.4/post-install.txt, shopware/core/6.4/public/index.php, shopware/core/6.6/post-install.txt
Change `bin/console`, `bin/ci` and `public/index.php` to be compatible with 6.6. This should improve the update flow a bit
=> Improve update from 6.5 to 6.6

frosh/code-quality-meta/0.3/root/rector.php
add Symfony 6.4 setlist, php 8.3 setlist, remove NameImportingPostRector since rector::rule method expects a RectorInterface
=> feat: Update rector recipe

shopware/storefront/6.6/bin/watch-storefront.sh
After creating a fresh setup, the first attempt to run the `watch-storefront.sh` script fails because the `var/plugins.json` file is still missing. 
```
> sw-next-storefront@1.0.0 hot-proxy
> NODE_ENV=development MODE=hot node ./build/start-hot-reload.js
/Users/tobiasberge/www/flex/vendor/shopware/storefront/Resources/app/storefront/webpack.config.js:58
throw new Error(`The file ${pluginFile} could not be found. Try bin/console bundle:dump to create this file.`);
^
```
You have to manually run `bin/console bundle:dump` to get it to run.
Adding `bundle:dump` to the script, similar to the shopware composer script (`composer watch:storefront`) so it works right away.
Also, when installing or removing extensions it is considered after re-starting the watcher.
=> Add bundle dump to storefront watch script

frosh/code-quality-meta/0.3/root/phpstan.neon.dist
Phpstan suggests replacing deprecated config option `checkMissingIterableValueType` with `missingType.iterableValue ` if we want to continue ignoring missing typehints from arrays.
https://phpstan.org/error-identifiers/missingType.iterableValue
=> Replace deprecated phpstan config option

shopware/k8s-meta/1.0/config/packages/operator.yaml
We're currently getting an error like this when trying to `composer update` with this recipe:
```
Symfony\\Component\\DependencyInjection\\Exception\\EnvParameterException: Incompatible use of dynamic environment variables \"K8S_CACHE_TYPE\"
```
I've updated the config according to [this hint](https://github.com/symfony/symfony/issues/20850#issuecomment-266047338) by the Symfony team.
=> fix: incompatible use of dynamic environment variable

shopware/k8s-meta/1.0/config/packages/operator.yaml
This will fix a current issue with the operator. From my perspective this should be named cache and not the technology which is used for the cache. But I'm open to change this also in the operator.
=> fix: set correct environment variables for cache adapter

shopware/platform/6.6/manifest.json, shopware/storefront/6.6/manifest.json
See #126
Also we need to adjust the shopware installer.
https://github.com/shopware/shopware/blob/trunk/src/Core/Installer/Configuration/EnvConfigWriter.php#L59
https://github.com/shopware/shopware/blob/trunk/src/WebInstaller/Services/FlexMigrator.php#L78
=> Update proxy_url key

shopware/administration/6.4/bin/build-administration.sh, shopware/administration/6.6/bin/build-administration.sh, shopware/storefront/6.4/bin/build-storefront.sh, shopware/storefront/6.6/bin/build-storefront.sh
in my .bashrc i have
```
export CDPATH="./:$HOME/projects"
```
$ bin/build-storefront.sh
/home/me/projects/example.com/bin/console: No such file or directory
The error message is a bit misleading, because that file actual does exist
```
~/projects/example.com$ CWD="$(cd -P -- "$(dirname -- "bin/build-storefront.sh")" && pwd -P)"
~/projects/example.com$ echo $CWD
./bin /home/me/projects/example.com/bin
```
So there is an additional output of the full directory.
This is because, if $CDPATH is set, `cd` prints the directory it changed to.
The fix is to unset CDPATH within the scripts scope.
This avoids also to `cd` to a very wrong directory
=> Fix build scripts if CDPATH is set Bash

shopware/core/6.7/bin/.htaccess, shopware/core/6.7/bin/build-js.sh, shopware/core/6.7/bin/ci, shopware/core/6.7/bin/console, shopware/core/6.7/bin/functions.sh, shopware/core/6.7/config/jwt/.gitignore, shopware/core/6.7/config/packages/shopware.yaml, shopware/core/6.7/custom/.htaccess, shopware/core/6.7/files/.htaccess, shopware/core/6.7/manifest.json, shopware/core/6.7/post-install.txt, shopware/core/6.7/public/.htaccess.dist, shopware/core/6.7/public/index.php, shopware/core/6.7/public/maintenance.html, shopware/core/6.7/root/.htaccess, shopware/core/6.7/var/.htaccess
Removes media Fallback in .htaccess for:
/theme/* /media/* /thumbnail/* /bundles/* /css/* /fonts/* /js/* /recovery/* /sitemap/*
With this, fallback handling, is the same as on caddy
Implanted for Shopware 6.7  as requested in https://github.com/shopware/shopware/pull/4730
=>  don't use a media Fallback for static assets ( #1461 ) 

open-telemetry/opentelemetry-logger-monolog/1.0/config/packages/prod/opentelemetry_logger_monolog.yaml, open-telemetry/opentelemetry-logger-monolog/1.0/manifest.json, shopware/opentelemetry/0.1/config/packages/prod/opentelemetry.yaml
With the current version of OpenTelemetry recipe, if configuration keys for monolog main handler are being merged with monolog configuration from docker, end config for main handler contains keys not supported by OpenTelemetry monolog handler.
Updated version extracts opentelemetry monolog handler to a separate recipe, that is executed only when `open-telemetry/opentelemetry-logger-monolog` package is installed. Configuration is based on configuration from the docker recipe, making them compatible.
=> fix: opentelemetry logging configuration

shopware/k8s-meta/1.0/config/packages/operator.yaml
This pull request includes a small change to the `shopware/k8s-meta/1.0/config/packages/operator.yaml` file. The change adds a new configuration option for `runtime_extension_management` under the `deployment` section (see [documentation](https://developer.shopware.com/docs/guides/hosting/installation-updates/extension-managment.html#configuring-extension-manager-to-read-only-in-admin))
* [`shopware/k8s-meta/1.0/config/packages/operator.yaml`](diffhunk://#diff-a019c3b6407301585db50547ad2fe0c9239bfd700e5c877c66a39cd331c9ff8aR25): Added `runtime_extension_management` option set to `false` in the `deployment` section.
=> feat(k8s-meta): Disable plugin management from the UI

shopware/storefront/6.6/bin/watch-storefront.sh, shopware/storefront/6.7/bin/watch-storefront.sh
In combination with this PR: https://github.com/shopware/shopware/pull/6328
It allows you to run the watch-storefront command without interaction and without knowing the theme-id (which changes everytime)
```
./bin/watch-storefront MyTheme
```
=> feat: Added argument support for watch-storefront command 

.github/workflows/nightly.yml
trunk needs `shopware/conflicts:>=0.4.0`
=> chore(ci): update conflicts package for trunk

shopware/administration/6.7/bin/build-administration.sh, shopware/administration/6.7/bin/watch-administration.sh
The vite build and dev scripts where not working because of missing environment variables. Additionally I noticed that the watch-administration.sh script did not respect both setup with seperate bundles and shopware/platform.
=> fix: vite 6.7

frosh/code-quality-meta/0.3/vendor-bin/phpstan/composer.json
The package `symplify/phpstan-rules` depends on the `nette/utils` v3.2.10 which requires php >=7.2 <8.4.
The version v11.3 of  `symplify/phpstan-rules` works with PHP 8.4.
=> fix: Update symplify/phpstan-rules to version ^11.3

frosh/code-quality-meta/0.4/root/rector.php, frosh/code-quality-meta/0.5/root/rector.php
Including all PHP level sets is redundant. Rector's level sets work because each higher level set includes all the rules from the lower level sets. So when you specify LevelSetList::UP_TO_PHP_84, it already contains all the rules from UP_TO_PHP_83, UP_TO_PHP_82, and UP_TO_PHP_81.
- Removed SYMFONY_54, SYMFONY_60, SYMFONY_61, and SYMFONY_62 since they're already included in SHOPWARE_6_5_0
- Removed SYMFONY_63 and SYMFONY_64 since they're already included in SHOPWARE_6_6_0
=> feat: Update Rector configuration and remove redundancy

shopware/administration/6.7/bin/build-administration.sh, shopware/administration/6.7/bin/watch-administration.sh
Dev dependencies shouldn't be required for the package to be built. In the future, commercial will not be buildable in alternative ways, such as as a composer dependency, without this change.
=> fix: install only prod dependencies

shopware/paas-meta/6.4/.platform/applications.yaml, shopware/paas-meta/6.5/.platform/applications.yaml, shopware/paas-meta/6.6/.platform/applications.yaml
the low_priority queue is missing in the consumer call for paas
=> fix: paas: add low_prioriy to message:consume

shopware/paas-meta/6.4/.platform/applications.yaml, shopware/paas-meta/6.4/.platform/services.yaml, shopware/paas-meta/6.4/config/packages/paas.yaml, shopware/paas-meta/6.5/.platform/applications.yaml, shopware/paas-meta/6.5/.platform/services.yaml, shopware/paas-meta/6.5/config/packages/paas.yaml, shopware/paas-meta/6.6/.platform/applications.yaml, shopware/paas-meta/6.6/.platform/services.yaml, shopware/paas-meta/6.6/config/packages/paas.yaml
fixes https://github.com/shopware/recipes/issues/176
adds a persistent redis session config for platform.sh
https://github.com/shopware/paas-meta/blob/main/platformsh-env.php has the logic already and sets a env var SESSION_REDIS_URL if a redissession relationship is found. 
that url is now used as session-url instead of CACHE_URL
=> feat: add persistent redis-cache for paas

shopware/core/6.7/public/.htaccess.dist
This PR updates the `.htaccess` rewrite conditions to **_exclude_** `/sitemap.xml` from being treated as a static file.  
Previously, adding `sitemap` to the list of exclusions caused a `404 Not Found`, as Shopware dynamically generates the sitemap via Symfony routes.
Fixes: https://github.com/shopware/shopware/issues/8091
=> fix: route sitemap through storefront controller

shopware/core/6.7/public/.htaccess.dist
As mentioned in [this issue](https://github.com/shopware/recipes/issues/183), the regex to rewrite queries to the front controller should be added a slash at the end so URLs like `/themenwelten` for example will not result in a 404.
closes https://github.com/shopware/recipes/issues/183
=> fix(htaccess): update rewrite condition

shopware/k8s-meta/1.0/config/packages/operator.yaml
This pull request introduces a new configuration for the `sitemap` in the `shopware` operator's Kubernetes meta package. The update adds support for storing sitemaps in an Amazon S3 bucket.
* Added a `sitemap` section in `shopware/k8s-meta/1.0/config/packages/operator.yaml` to configure Amazon S3 as the storage type. This includes specifying the bucket, region, endpoint, and public visibility settings.
=> configured Shopware to proxy sitemap files

shopware/administration/6.7/bin/build-administration.sh, shopware/administration/6.7/bin/watch-administration.sh, shopware/platform/6.7/bin/build-administration.sh, shopware/platform/6.7/bin/build-storefront.sh, shopware/platform/6.7/bin/watch-administration.sh, shopware/platform/6.7/bin/watch-storefront.sh, shopware/storefront/6.7/bin/build-storefront.sh, shopware/storefront/6.7/bin/watch-storefront.sh
When building administration/storefront of a plugin which only contains a package.json but no node_modules and package-lock.json, the build scripts create a package-lock.json with relative paths to the plugin's node_modules folder.
To fix this, I've changed the `npm install` commands to change directory into `$path` beforehand and removed the `--prefix=$path` from the install command.
Before:
`npm install --omit=dev --prefix "$path" --no-audit --prefer-offline`
After:
`(cd "$path" && npm install --omit=dev --no-audit --prefer-offline)`
=> chore: prevent relative paths in plugin package-lock.json files
